#!/bin/bash
#
# 
#
# Copyright (c) 2022 rickicode. Released under the MIT License.
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


if [[ $# -gt 0 ]]; then
    client="$1"
fi

while [[ -z "$client" ]];
do
    read -p "Enter name: " client
done

sed -i "/^# BEGIN_PEER $client /,/^# END_PEER $client$/d" /etc/wireguard/wg0.conf
rm -rf /root/akun/wg/"$client.conf"
rm -rf /root/akun/wg/"$client.txt"


echo
echo "$client removed!"
	
